# The dev container of the container and generic projects, by digest, so that Renovate keeps it
# current. https://github.com/Dennis-Otto/repo-blueprint
FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04@sha256:d94c97dd9cacf183d0a6fd12a8e87b526e9e928307674ae9c94139139c0c6eae
