# The dev container of the php projects, by digest, so that Dependabot keeps it
# current. https://github.com/Dennis-Otto/repo-blueprint
FROM mcr.microsoft.com/devcontainers/php:8.5@sha256:62cbc2db4a4a310f3b57f42e1574ef57dfb2e903d4afbc4fb808d7ac73a3c13a
