# The dev container of the php projects, by digest, so that Dependabot keeps it
# current. https://github.com/Dennis-Otto/repo-blueprint
FROM mcr.microsoft.com/devcontainers/php:8.2@sha256:83adf3c89992a495705516a8ebe4ebcd2d8cb6e8176782a4dadfdd26df736f25
