# The dev container of the node projects, by digest, so that Renovate keeps it
# current. https://github.com/Dennis-Otto/repo-blueprint
FROM mcr.microsoft.com/devcontainers/typescript-node:24@sha256:cba90c28e53ac2f5a8a5a0388b71b8e98bbe1a4711e0faaa6ef48b137037d4ae
